# Generated by Django 5.1.1 on 2024-09-27 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_creado_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
