# Generated by Django 5.1.1 on 2024-09-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_categoria_creado_en_producto_creado_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='creado_en',
            new_name='fecha_creacion',
        ),
    ]
